name: smart_microbus
description: "Smart Microbus Application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

# =========================
# Dependencies
# =========================
dependencies:
  animate_do: ^5.1.0
  animated_text_kit: ^4.3.0
  bloc: ^9.0.0
  build_runner: ^2.6.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.1
  dropdown_button2: ^3.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.3.0
  flutter_screenutil: ^5.9.3
  geolocator: ^14.0.2
  get_it: ^9.2.0
  google_fonts: ^8.1.0
  http: ^1.6.0
  image_cropper: ^12.1.0
  image_picker: ^1.2.1
  implicitly_animated_list: ^2.3.0
  intl: ^0.20.2
  json_annotation: ^4.10.0
  json_serializable: ^6.12.0
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.1
  lottie: ^3.3.3
  mobile_scanner: ^7.2.0
  pinput: ^6.0.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0
  retrofit_generator: ^10.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  signalr_netcore: ^1.4.4
  smooth_page_indicator: ^2.0.1

# =========================
# Dev Dependencies
# =========================
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# =========================
Flutter Launcher Icons Config:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/waslaLogo.png
  min_sdk_android: 21
  remove_alpha_ios: true

# =========================
# Flutter Section
# =========================
flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/animations/
